spring.application.name=jobtrackr-api
spring.datasource.url=jdbc:h2:mem:proddb
spring.jpa.hibernate.ddl-auto=update
jwt.secret=cambia-esto-por-un-secreto-largo-y-aleatorio-de-al-menos-32-caracteres
jwt.expiration-ms=86400000
